### ISSUE TITLE
Host app and api in constant

### ISSUE THREAD

**Issue by nums** [blastream/wordpress-plugin#1]
It will be better to have something like this :
define('BLASTREAM_APP_URL', 'app.v2.blastream.com'); 
define('BLASTREAM_API_URL', 'api.v2.blastream.com'); 

at the start of the script

**Comment by Reyemneirda** [comment]
fix in [31f50ea](https://github.com/blastream/wordpress-plugin/commit/31f50ea9cd2ce2a0fdd4efab4efd16502e33ad8b)
